# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-tags:
      runs-on: ubuntu-latest
      outputs:
        tag: ${{ steps.anothr-Nick.outputs.tag }}
        new_tag: ${{ steps.anothr-Nick.outputs.new_tag }}
      steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Generate tags
        id: anothr-Nick
        uses: anothrNick/github-tag-action@1.36.0
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          WITH_V: true
          DRY_RUN: True
    
  testing-if:
       needs: generate-tags
       if: needs.generate-tags.outputs.new_tag!=needs.generate-tags.outputs.tag
       runs-on: ubuntu-latest
       steps:
       - run: echo ${{ needs.generate-tags.outputs.new_tag }}
        
  
#   build-and-publish:
    
#     needs: generate-tags
#     if: ${{ needs.generate-tags.outputs.tag }}!=""
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v3
#       with:
#         fetch-depth: '0'
#     - name: Set up JDK 11
#       uses: actions/setup-java@v3
#       with:
#         java-version: '11'
#         distribution: 'temurin'
#         server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
#         settings-path: ${{ github.workspace }} # location for the settings.xml file
      
#     - name: Build with Maven
#       run: mvn -B package --file pom.xml       
        
#     - name: Update version
#       run: mvn versions:set -DnewVersion=${{ needs.generate-tags.outputs.tag }}

#     - name: Commit Version
#       run: mvn versions:commit 
        
#     - name: publish version
#       run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#       env:
#         GITHUB_TOKEN: ${{  secrets.RELEASE_TOKEN  }}
        
#   create-release:
#     needs: [build-and-publish, generate-tags]
#     runs-on: ubuntu-latest    
#     steps:
#     - uses: actions/checkout@v3
    
#     - name: Create a Release
#       uses: elgohr/Github-Release-Action@v4
#       env:
#         GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
#       with:
#         title: ${{ needs.generate-tags.outputs.tag }}

#   update-tag:
#     needs: create-release
#     runs-on: ubuntu-latest
      
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         fetch-depth: '0'
#     - name: Bump version and push tag
#       uses: anothrNick/github-tag-action@1.36.0
#       env:
#         GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
#         WITH_V: true
